name: Private action user
run-name: Using private action
on: 
  push:
  workflow_dispatch:
    inputs: 
      get-name:
        default: test
  repository_dispatch:
      types: 
        - my-event
jobs:
  Provate-action-demo:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ inputs.get-name }}
    - run: echo ${{ github.event.client_payload.inputs.get-name }}


